nginx_dir: "/etc/nginx"
nginx_conf_dir: "{{nginx_dir}}/sites-available"
nginx_sites_dir: "{{nginx_dir}}/sites-enabled"
nginx_access_log: "/srv/www/logs/{{item.project_name}}/logs/access.log"
nginx_error_log: "/srv/www/logs/{{item.project_name}}/logs/error.log"
project_parent: "/srv/www/projects/"